dashboard_import:
  package_import_url: github://MariuszWoszczynski/wmbus-reader-eth/wmbus-reader-eth.yaml@main
  import_full_config: true

substitutions:
  name: "wmbus-reader-eth"
  friendly_name: "WMBUS Reader ETH"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader_eth
    version: "1.0"
#  compile_process_limit: 1    # only for RPI 

esp32:
  board: wt32-eth01
  framework:
    type: arduino


external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus ]
    refresh: 0d
    
    
time:
 - platform: sntp
   id: time_sntp

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nq6GQFDVaPbFk9HNVzvtiI+FnePMbnlq3zLv4H1Y/so="

ota:
  - platform: esphome


web_server: 
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  #Optional manual IP
#  manual_ip:
#    static_ip: 192.168.10.220
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0


#wmbus:             
#  mosi_pin: GPIO15
#  clk_pin:  GPIO12
#  miso_pin: GPIO04
#  gdo2_pin: GPIO35
#  gdo0_pin: GPIO14
#  cs_pin:   GPIO02
#  log_unknown: true
